[package]
name = "warp-hello"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.10.5"
tokio = { version = "1.13.0", features = ["full"] }
warp = { version = "0.3.1", features = ["tls"] }
